language: java
jdk:
  - oraclejdk8

before_install:
  - wget https://github.com/tcurdt/jdeb/archive/1d163230de6091efa8daeafa8289239d9ed1d88e.zip
  - unzip 1d163230de6091efa8daeafa8289239d9ed1d88e.zip
  - cp -rT jdeb-1d163230de6091efa8daeafa8289239d9ed1d88e ./
  - rm -r jdeb-1d163230de6091efa8daeafa8289239d9ed1d88e
  - rm 1d163230de6091efa8daeafa8289239d9ed1d88e.zip
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts
  - pip install --user codecov

after_success:
  - mvn clean test jacoco:report coveralls:report
  - codecov
